name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=lehues28_HRM_Project
            -Dsonar.organization=lehues28
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
